### ISSUE TITLE
Key Errors

### ISSUE THREAD

**Issue by duhby** [Obsidion-dev/asyncpixel#238]
## mcVersionRp
**Describe the bug**
When getting the player object of a user, there is sometimes a key error for "mcVersionRp." Not sure why this bug occurs, but it might be an api setting through hypxiel, or just a bug with this specific player.

**To Reproduce**
Try to get the player object with the uuid: "4ffa3b3abeb64fee89a0f7697c55c92c" (or "f775e05a15e24c01b82b1847fd149de5") and this error occurs.

**Expected behavior**
No error occurs and mc_version_rp is set to None (should be changed to an Optional[str])

**Screenshots**
![image](https://user-images.githubusercontent.com/59372145/120362336-f55a6a80-c2d8-11eb-9582-efe45a148962.png)

No further context is needed.

## modes
**Describe the bug**
When using asyncpixel.Hypixel.game_count(), there is a key error for "modes" when trying to access the modes of gamemodes on hypixel that have no subsequent modes.

**To Reproduce**
Call the game_count() function on a valid Hypixel object.

**Expected behavior**
There is no error and "modes" in GameCountsGame should be an Optional[Dict[str, int]]

**Screenshots**
![image](https://user-images.githubusercontent.com/59372145/120368022-8e8c7f80-c2df-11eb-9509-167d0bb13817.png)

No further context is needed.

## joinable
**Describe the bug**
When trying to create a guild object of some guilds, a key error is raised for "joinable." (this includes guild_by_player, guild_by_name, and most likely guild_by_id)

**To Reproduce**
Use guild_by_player("f775e05a15e24c01b82b1847fd149de5") on a valid Hypixel object and you will get the error.

**Expected behavior**
There is no error and "joinable" is defaulted to False. (Not sure why this error occurs with this guild, but it does.)

**Screenshots**
![image](https://user-images.githubusercontent.com/59372145/120369803-d0b6c080-c2e1-11eb-837a-fe93a6354c57.png)

No further context is needed.

## death_count
**Describe the bug**
When trying to get the skyblock profile of a player, there is sometimes a key error for "death_count." (probably because they have no deaths)

**To Reproduce**
Call profile("4ffa3b3abeb64fee89a0f7697c55c92c") on a valid Hypixel object.

**Expected behavior**
There is no error and "death_count" is defaulted to 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/59372145/120372006-a1ee1980-c2e4-11eb-8351-95cdbb1e0af2.png)

No further context is needed.

## other key errors
I won't bother typing these out and getting screenshots but there are also key errors for:
- "coin_purse" when calling profiles("af8ffc3e9afc4d35a61d2db15462c8a4")
- "death_count" when calling profiles("4ffa3b3abeb64fee89a0f7697c55c92c")
- "first_join_hub" when calling profiles("f775e05a15e24c01b82b1847fd149de5")
- and probably more

## not a key error but similar issue
**Describe the bug**
When trying to get the skyblock profile of a player, a TypeError is sometimes raised

**To Reproduce**
Call profile("af8ffc3e9afc4d35a61d2db15462c8a4") on a valid Hypixel object.

**Expected behavior**
There is no error and the data that isn't available in the api is defaulted to some value.

**Screenshots**
![image](https://user-images.githubusercontent.com/59372145/120372728-89323380-c2e5-11eb-8d4f-0e4219d20a11.png)

No further context is needed.

## also not a key error, but similar issue
**Describe the bug**
When trying to get the recent_games of some players, a pydantic ValidationError is raised.

**To Reproduce**
Call recent_games("f775e05a15e24c01b82b1847fd149de5") on a valid Hypixel object.

**Expected behavior**
There is no error. (Not entirely sure how it works in the back end so I can't provide further details.)

**Screenshots**
![image](https://user-images.githubusercontent.com/59372145/120374156-335e8b00-c2e7-11eb-96ad-0aff7c043946.png)

No further context is needed.

**Comment by Darkflame72** [comment]
@all-contributors please add @duhby for bug.

**Comment by Darkflame72** [comment]
Ok this one has a couple issues in it so might take a bit longer.
