### ISSUE TITLE
Missing keys (again)

### ISSUE THREAD

**Issue by duhby** [Obsidion-dev/asyncpixel#248]
mcVersionRp is still sometimes a missing key in version 1.0.10 cuz this wasn't changed (uuids that have this error: "f775e05a15e24c01b82b1847fd149de5" and "4ffa3b3abeb64fee89a0f7697c55c92c")
https://github.com/Obsidion-dev/asyncpixel/blob/d7a74c6c1a359a51db53b3b5b98783ecac0d4bb0/asyncpixel/hypixel.py#L521

**Comment by Darkflame72** [comment]
Thanks, I have a found a couple others so am going through testing all the endpoints and will be releasing a new version early to mid next week with a fix
