### ISSUE TITLE
'AttributeError' when trying to access data

### ISSUE THREAD

**Issue by TwoSails** [Obsidion-dev/asyncpixel#3]
When the guild object is returned from the 'get_guild_by_name', I don't know how to get the information about the guild after that.

Code:
```
api = client.Client('API TOKEN')
guild = api.get_guild_by_name('GUILD NAME')

print(guild.description) # This is where the error happens
```

I was wondering if an example could also be put in the repository too.

**Comment by Darkflame72** [comment]
This library is asynchronous so you will have to have it in an Aston loop and use await in the function call. I will put some examples up tomorrow as am away from my laptop at the moment.

**Comment by TwoSails** [comment]
Ok, thank you

**Comment by Darkflame72** [comment]
An easy way to do that would be:
```python
import asyncpixel
import asyncio

uuid = "405dcf08b80f4e23b97d943ad93d14fd"


async def main():
    client = asyncpixel.Client("API TOKEN")
    guild = await client.get_guild_by_name('GUILD NAME')
    print(guild.description)
    await client.close()


asyncio.run(main())
```
