### ISSUE TITLE
Fix error F821 in actions

### ISSUE THREAD

**Issue by aiexz** [Obsidion-dev/asyncpixel#7]
Add `--ignore F821` argument to flake8 in actions in order to mark builds as successful or there is another solution on [stackoverflow](https://stackoverflow.com/questions/37840142/how-to-avoid-flake8s-f821-undefined-name-when-has-been-installed-by-get)

**Comment by Darkflame72** [comment]
This was more due to a variable naming error in the status model which has now been fixed.

**Comment by Darkflame72** [comment]
@all-contributors please add @aiexz for bug reports
