### ISSUE TITLE
Class for profiles

### ISSUE THREAD

**Issue by aiexz** [Obsidion-dev/asyncpixel#9]
**Describe the solution you'd like**
Create a class to serialize get_profiles() method

**Describe alternatives you've considered**
Do nothing(return arrays as now)

**Comment by Darkflame72** [comment]
I can add a class to serialise it and it will take a little while as there are numerous different responses depending on the players privacy settings as detailed [here](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/skyblock/profiles.md) I should be able to get a fix for this and any others like this out by the end of the week.

**Comment by Darkflame72** [comment]
This is fixed with Version 1
